export const items = [{
        id: 1,
        name: "Hoodies",
        price: 14.0,
        image: "assets/images/featured1.png",
        category: "hoodies",
        quantity: 10,
    },
    {
        id: 2,
        name: "Shirts",
        price: 24.0,
        image: "assets/images/featured2.png",
        category: "shirts",
        quantity: 15,
    },
    {
        id: 3,
        name: "Sweatshirts",
        price: 24.0,
        image: "assets/images/featured3.png",
        category: "shirts",
        quantity: 20,
    },
];